services:    

  frontend:
    container_name: aisearch-frontend
    image: vishnu1001/aisearch-frontend
    # build:
    #   context: ./frontend
    ports:
      - 3000:3000
    networks:
      - aisearch
  
  # backend:
  #   container_name: aisearch-backend
  #   image: vishnu1001/aisearch-backend
  #   # build:
  #   #   context: ./backend
  #   volumes:
  #     - ./data/:/app/data
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - aisearch

  nginx:
    image: vishnu1001/aisearch-nginx
    container_name: aisearch-nginx
    ports:
      - 80:80
    networks:
      - aisearch
    depends_on:
      - frontend
      # - backend

networks:
  aisearch:
    external: true
    name: aisearch